### ISSUE TITLE
Multiple Code Errors

### ISSUE THREAD

**Issue by ingeniousgenius** [crashoverride777/swifty-receipt-validator#1]
Hi, when I add the files I get an 3 errors and a fail warning.

The First error comes up here (Line 328)
                   `let receiptBundleID = receipt[ReceiptInfoField.bundle_id.rawValue] as? String ?? "NoReceiptBundleID`

> Binary operator '??' cannot be applied to operands of type '[String : AnyObject]?' and 'String'

The seconds comes up at Line 351
`receiptProductID = receiptInApp[ReceiptInfoField.InApp.product_id.rawValue] as? String ?? "NoReceiptProductID"`

> Ambiguous use of 'subscript'

The third comes up at Line 328
`let receiptBundleID = receipt[ReceiptInfoField.bundle_id.rawValue] as? String ?? "NoReceiptBundleID"`

> Ambiguous use of 'subscript'

And just a plain warning saying

> Cast from 'MDLMaterialProperty?!' to unrelated type '[AnyObject]' always fails

At line 343 
`guard let inApp = receipt[ReceiptInfoField.in_app.rawValue] as? [AnyObject] else`

I'll have a go at it myself and see what I can do

**Comment by crashoverride777** [comment]
Hey, Thanks for your feedback. I just checked the code with Swift 2 and I get no errors. Are you on Swift 3? I haven't updated the code yet for Swift 3

**Comment by ingeniousgenius** [comment]
I was using Swift 2.2 I think but I fixed the errors by casting the `AnyObject` as an `NSDictionary.` I just installed the beta version of Xcode and I'm going to begin using Swift 3 so I might be able to contribute to the repo.

**Comment by crashoverride777** [comment]
Hey, That is strange, I am not getting any errors in the project.

**Comment by ingeniousgenius** [comment]
I'm using Swift 3 currently and the only error is on line `241` 

> Ambiguous reference to member 'dataTask(with:completionHandler:)'

on the code `let task = URLSession.shared.dataTask(with: request) { [unowned self] (data, response, error) in
`

**Comment by crashoverride777** [comment]
Hey, you shouldn't have had any errors with swift 2 as well, not sure what happened. In regards to the swift 3  thing you will have to wait for 1-2 more weeks until I upgrade. If you have a fix in the mean time please let me know.

**Comment by ingeniousgenius** [comment]
I fixed the swift two errors by casting the `Any` to an `NSDictionanry` also, It's fully compatible with swift 3, I just changed the request from a `NSMutableURLRequest` to an `NSURLRequest` and changed it from a `let` to a `var`. All the other errors can be fixed with a click. So far so good

**Comment by crashoverride777** [comment]
Cool, thanks for sharing. I will fully update this helper when swift 3 is officially out.

**Comment by ingeniousgenius** [comment]
No worries, I'll add the official changes later

**Comment by crashoverride777** [comment]
Thank you very much. I will keep this issue open for now, swift 3 should be out soon. Remember to test everything properly.

**Comment by ingeniousgenius** [comment]
I finally fixed the 1,268 errors in my code after updating to swift 3, so I'm ready to test!

**Comment by crashoverride777** [comment]
Go for it. You can check the print statements incase something gets stuck somewhere.

**Comment by ingeniousgenius** [comment]
Works perfectly on the latest ios 10 beta and Swift 3. This was the debugger responce.

```
Receipt found
Starting receipt validation
Receipt validation failed: URL request - Invalid receipt status in json response = 21007
Receipt validation failed: Production url used in sandbox mode, trying sandbox url...
Valid receipt status in json reponse: 0

URL request - Valid receipt in json reponse = {
    "adam_id" = 0;
    "app_item_id" = 0;
    "application_version" = 742;
    "bundle_id" = "com.flatboxstudio.numbertap";
    "download_id" = 0;
    "in_app" =     (
            {
        "is_trial_period" = false;
        "original_purchase_date" = "2016-03-26 21:03:41 Etc/GMT";
        "original_purchase_date_ms" = 1459026221000;
        "original_purchase_date_pst" = "2016-03-26 14:03:41 America/Los_Angeles";
        "original_transaction_id" = 1000000201757178;
        "product_id" = "com.flatboxstudio.numbertap.removeAds";
        "purchase_date" = "2016-03-26 21:03:41 Etc/GMT";
        "purchase_date_ms" = 1459026221000;
        "purchase_date_pst" = "2016-03-26 14:03:41 America/Los_Angeles";
        quantity = 1;
        "transaction_id" = 1000000201757178;
    }
);
    "original_application_version" = "1.0";
    "original_purchase_date" = "2013-08-01 07:00:00 Etc/GMT";
    "original_purchase_date_ms" = 1375340400000;
    "original_purchase_date_pst" = "2013-08-01 00:00:00 America/Los_Angeles";
    "receipt_creation_date" = "2016-09-04 09:49:57 Etc/GMT";
    "receipt_creation_date_ms" = 1472982597000;
    "receipt_creation_date_pst" = "2016-09-04 02:49:57 America/Los_Angeles";
    "receipt_type" = ProductionSandbox;
    "request_date" = "2016-09-04 09:50:00 Etc/GMT";
    "request_date_ms" = 1472982600100;
    "request_date_pst" = "2016-09-04 02:50:00 America/Los_Angeles";
    "version_external_identifier" = 0;
}

URL request - Receipt verification successful
Receipt validation passed in sandbox mode, unlocking product(s)
```

If you want I can attach the updates swift files or make a gist with them. Up to you 👍

**Comment by crashoverride777** [comment]
Awesome, thank you very much for sharing. Remember to test when your app is in release mode, not just debug mode. Dont worry about attaching the updates, I will get the xCode GM on wednesday after the keynote and will update all my gitHub projects ASAP. Thanks again for your feedback, very kind.

**Comment by ingeniousgenius** [comment]
No worries, I'll test it in production when I setup test flight hopefully 👍

**Comment by crashoverride777** [comment]
Great. I will still leave this issue open until I upgraded to Swift 3. Thanks again and happy coding.

**Comment by crashoverride777** [comment]
Updated to Swift 3. I will close this issue now. Please dont hesitate to report any other issues you find. Thanks again
