### ISSUE TITLE
Make log output to the console - optional

### ISSUE THREAD

**Issue by AdAvAn** [crashoverride777/swifty-receipt-validator#10]
**SwiftyReceiptValidator** - actively reports on all its actions, sometimes want to disable it.
I suggest adding a new parameter in "**Configuration**" so that it is possible to disable logging if necessary.

**Comment by crashoverride777** [comment]
Hey, thank you for your comment. I’m planning on releasing an update very soon and will include an option to disable logging. Thanks again for your feedback

**Comment by crashoverride777** [comment]
Hey,

sorry been a bit busy recently. I am currently working on adding Swift-Package-Manager support and will also add the option to disable logging. Update should be released very soon.

**Comment by crashoverride777** [comment]
Hey, 

my apologies for the delay. I just release v6.0.0, which includes a isLoggingEnabled boolean. Please check the readme again after updating, the update includes some small source breaking changes.

Thanks again for your feedback.
