### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by thejeff77** [crashoverride777/swifty-receipt-validator#11]
Hey there! Thanks for putting out something new with support for Swift 5, etc.. Any chance this could be made available with the new SPM?

**Comment by crashoverride777** [comment]
Hey,

Thanks for your feedback

I just released v6.0.0 but could not put in the SwiftPackageManager support. I am working on this for another update very soon.

**Comment by crashoverride777** [comment]
Hey,

I started the package manager support yesterday. I think I am mostly done, just need to do a bit of testing and also make sure that CocoaPods is not broken. I will try to push this update out this week.

**Comment by thejeff77** [comment]
@crashoverride777 I'm about ready to integrate with this. I'll checkout your branch this weekend if you haven't made it around to testing & merging. Thanks.

**Comment by crashoverride777** [comment]
Hey,

I am so sorry, I did not get around to test this yet. I believe it should be ready, just want to double check that it did not break cocoa pods. Its my first time integrating swift package manager. I’ll try to get it done this weekend.

**Comment by crashoverride777** [comment]
Hey, 

I got the swift package manager working, just tested with a sample app and it works as expected. Will just check the cocoa pods and the update should be out latest tomorrow. 

Thanks for your patience.

**Comment by crashoverride777** [comment]
Hey,

I just pushed v6.1.0 with the swift package manager support. If you have any problems please do not hesitate to open another issue.
