### ISSUE TITLE
Feature Request - get original bundle version & app version

### ISSUE THREAD

**Issue by thejeff77** [crashoverride777/swifty-receipt-validator#12]
Hey there!

I was wondering how hard it might be to add verification of the more global fields on a local receipt - like the original app version as documented here: https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html

It would be awesome to have these parsed and a flow setup to get that string. 

Let me know what you think and if it is possible. If you have time to do it that would be awesome.

**Comment by crashoverride777** [comment]
Hey,

thanks for your comment and my apologies for late reply. You should have full access to the receipt response when you validate your receipt. 

```
receiptValidator.validate(validationRequest)` { result in
    switch result {
    case .success(let response):
         print(response.receiptResponse.receipt?.originalApplicationVersion)
    case .failure(let error):
      ...
   }
}
```
