### ISSUE TITLE
Error in docu

### ISSUE THREAD

**Issue by peterpaulis** [crashoverride777/swifty-receipt-validator#13]
https://github.com/crashoverride777/swifty-receipt-validator#validate-subscriptions

```
case .failure(let error):
        switch error {
        case .subscriptionExpired(let statusCode):
            // no active subscription found, update your cache/app etc
```

when a subscription is expired, the success branch is called and the response.validSubscriptionReceipts is empty

the error subscriptionExpired is NOT called as presented in the docu

**Comment by crashoverride777** [comment]
Hey,

thank you for your comment. I will investigate this ASAP.

**Comment by crashoverride777** [comment]
Hey, thanks again for the comment.

This particular error case is only returned if status code from receipt validation is 21006 and only gets returned for iOS 6 style transactions.

In Apples documents (https://developer.apple.com/documentation/storekit/in-app_purchase/validating_receipts_with_the_app_store) they mention to use the `latest_receipt_info` array to check for subscriptions, which is what the `response.validateSubscriptionReceipts` response does. It checks all subscriptions and returns an array of active ones, or empty if no active ones are left.

Its a bit confusing from the Apple documentation but `case .subscriptionExpired(let statusCode):` should only be returned if apple returns a 21006 code from the receipt validation, which would only happen for iOS 6 style transactions.

**Comment by crashoverride777** [comment]
I will update the document now

**Comment by crashoverride777** [comment]
Hey,

I will close this issue as it is correct behaviour. Please feel free to open another issue if you think its still not correct.
