### ISSUE TITLE
Parsing fails on rare cases where "download_id":null 

### ISSUE THREAD

**Issue by peterpaulis** [crashoverride777/swifty-receipt-validator#14]
We found having few rare cases of users having "download_id":null in their receipt

`"receipt":{"receipt_type":"Production",  "adam_id":1065010776, "app_item_id":1065010776,  "bundle_id":"sk.npress.dennikn.dennikn", "application_version":"53",  "download_id":null, "version_external_identifier":843649694, "receipt_creation_date":"2021-09-27 12:07:22 Etc/GMT", "receipt_creation_date_ms":"1632744442000", "receipt_creation_date_pst":"2021-09-27 05:07:22 America/Los_Angeles", 
`

Not sure why this is happening, but having "download_id":null results in failing to parse the response in `ReceiptClient`
`decoder.decode(SRVReceiptResponse.self, from: data)`

the "download_id":null  is also mentioned here, with a variant of "null"
https://developer.apple.com/forums/thread/658179

therefor SRVReceipt.downloadId should be `Int?` not `Int`

**Comment by crashoverride777** [comment]
Hey,

Thank you very much for your message and pointing this out. I will double check this tonight and make this field optional. Update will be released latest tomorrow.

Thanks again. 

Best regards

**Comment by crashoverride777** [comment]
Hey,

I have just published v6.3.0 with the optional `downloadId` field, should be live soon. It does sound like a rare case reading this apple developer chat, but I don't see any harm in making it optional.

Please do not hesitate to report any other issues you might face, its much appreciated. 

Thanks again
