### ISSUE TITLE
Set up before

### ISSUE THREAD

**Issue by RockySightingsApps** [crashoverride777/swifty-receipt-validator#2]
Hi, It me the pain in the butt again  😂. Im wondering (even though this is vaguely related to your project) how I can setup the purchases. I'm almost ready to submit my app for review and then I'll send you the link but I would like to incorporate iap to remove ads. Could I please have some help?

**Comment by crashoverride777** [comment]
Read this tutorial. Its in swift, and teaches you in app purchases in a nice and reusable way. https://www.raywenderlich.com/122144/in-app-purchase-tutorial

**Comment by crashoverride777** [comment]
You cannot rush in app purchases, you will have to test a lot.

**Comment by RockySightingsApps** [comment]
Thanks Ill check it out, and yea I've learned over the past week or so with slight little changes there is a lot of testing.

**Comment by crashoverride777** [comment]
Yeah, you really have to take your time with in app purchases. Also I would suggest you skip receipt validation for now and just focus on in app purchases.

**Comment by RockySightingsApps** [comment]
I did some work on iap and figured it out some what. Now I'm having issues w this: http://stackoverflow.com/questions/39906748/present-view-swift-3

**Comment by crashoverride777** [comment]
I answered your question. Hope this helps
