### ISSUE TITLE
Shared secret for auto-renewable subscriptions

### ISSUE THREAD

**Issue by sergesd** [crashoverride777/swifty-receipt-validator#3]
Hi,
Is it possible to use shared secret for auto-renewable subscriptions?
JSONObjectKey has 'password' key, but it seems currently it's not used.

**Comment by crashoverride777** [comment]
Hey,

I actually dont know to be honest. I have never used auto-renewable subscriptions in any of my apps before or worked with the StoreKit API for those.

Maybe google this, I think this tutorial talks about them

http://www.brianjcoleman.com/tutorial-receipt-validation-in-swift/

My apologises for that.

**Comment by sergesd** [comment]
Thanks for the link!
Now it works perfectly in your project:
`let payload = [JSONObjectKey.receiptData.rawValue: receiptData]`
changed to:
`let payload = [JSONObjectKey.receiptData.rawValue: receiptData, JSONObjectKey.password.rawValue: "sharedSecret"]`

**Comment by crashoverride777** [comment]
Hey,

Thanks very much for posting this. I will update the project in the future to include this. Happy coding

**Comment by crashoverride777** [comment]
Is that all you need to do for shared secret or did you need to change anything else? 

I was planning on maybe changing the code to something like this where you can pass in an optional shared secret string in the validation method

    func validateReceipt(forProductID: "SOMEID", sharedSecret: "SomeSharedSecret")....

and than I would change the payload bit to this 

    var payload = [JSONObjectKey.receiptData.rawValue: receiptData]
  
    if let sharedSecret = sharedSecret {
            payload.updateValue(sharedSecret, forKey: JSONObjectKey.password.rawValue)
    }

What do you think?

**Comment by sergesd** [comment]
Yes, and maybe instead of updateValue just:
`payload[JSONObjectKey.password.rawValue] = sharedSecret`

**Comment by crashoverride777** [comment]
Hey, thanks for the reply. I will push an update soon. 

Thanks for the syntax tip, I know you can actually do it that way. I usually like to use the helper methods when working with arrays etc as I think at first glance it makes the code more readable.

Thanks again.

**Comment by crashoverride777** [comment]
It will probably be tomorrow or something I want to read bit more about auto subscriptions. I am not sure that I am doing all the necessary check for them in the validation bit.

**Comment by crashoverride777** [comment]
I updated the helper. It is also now returning the response so you can do additional checks such as checking expiry date etc. Have a look at the instructions again when you update, I changed the API a bit to make this more readable.

Thanks for the feedback.
