### ISSUE TITLE
'InApp' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by achirkof** [crashoverride777/swifty-receipt-validator#5]
Hi @crashoverride777 !

Thank you for useful lib! Receipt validation for apple purchases is a real pain 😢 
I'm trying your lib and get an error. You have to make nested enum `InApp` also public `public enum InApp: String`

![image 2018-04-07 at 10 52 58 pm](https://user-images.githubusercontent.com/1292136/38459824-a432da22-3ab7-11e8-8182-1ee6e6716a78.png)

**Comment by crashoverride777** [comment]
Hey, Thank you for your comment, and sorry for my delayed reply. I will push an update soon, hopefully v3.0 with the new error handling also. Best regards

**Comment by crashoverride777** [comment]
Hey, finally released v3.0 with the new error handling. Also cleaned the project quite a bit. Just done my final testing and pushed the update. The are some source breaking changes, so please check the readme again. The `InApp` enum is now also public. Please feel free to open any issues if there is something you noticed. Thanks again for using this repo. Best regards and happy coding.
