### ISSUE TITLE
It is NOT conform to IAP best practices

### ISSUE THREAD

**Issue by 008v** [crashoverride777/swifty-receipt-validator#7]
* The signature of receipt is not verified by using openssl
* Never contact the apple server on the client

https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html#//apple_ref/doc/uid/TP40010573-CH1-SW2

**Comment by crashoverride777** [comment]
Hey, thanks for your comment. This is mentioned in the read me of the repo.

**Comment by BigToeProductions** [comment]
In the example code for the project we have this line
```
receiptValidator.validate(.purchase(productId: productId), sharedSecret: nil) { result in
                    defer {
                        queue.finishTransaction(transaction) // make sure this is in the validation closure
                    }
```
I wasn't following where .purchase came from.  Could you explain it for me?
Also I believe the "productId" should be "productIdentifier" to match the definition.  Not a big deal.

**Comment by crashoverride777** [comment]
Hey, I will close this issue now as with the newer version of this repository you can create your own config method to validate with your own webserver. Please do not hesitate to open a new issue if you still feel like something is wrong. It would be much appreciated.
