### ISSUE TITLE
Example clarification

### ISSUE THREAD

**Issue by BigToeProductions** [crashoverride777/swifty-receipt-validator#8]
In the example code for the project we have this line

```
 let productIdentifier = transaction.payment.productIdentifier
            
                receiptValidator.validate(.purchase(productId: productId), sharedSecret: nil) { result in
                    defer {
                        queue.finishTransaction(transaction) // make sure this is in the validation closure
                    }
```
I wasn't following where .purchase method came from. Could you clear that up for me?
Also I believe the "productId" should be "productIdentifier" to match the definition. Not a big deal.

**Comment by crashoverride777** [comment]
Hey,

Thank you very much for using my repo. My apologies about the documentation errors, I must have deleted some comments by accident. I released v4 yesterday with updated documentation. Please let me know if that helps.

**Comment by crashoverride777** [comment]
Hey, I just pushed another small update and tweaked the documentation. I will close this issue, if you have any further problems, please do not hesitate to open another issue.

Best regards
